services:
  lyricser:
    build: .
    restart: unless-stopped
    command: sh -c "npm install --no-audit --no-fund && node index.js"
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - BASE_PATH=/lyricser
      - ADMIN_USERNAME=sc
      - ADMIN_PASSWORD=sc123698745